# Generated by Django 4.2.2 on 2023-06-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=225)),
                ('Username', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=50)),
                ('Phone_number', models.IntegerField(max_length=17)),
            ],
        ),
    ]
